### ISSUE TITLE
Invalid device function

### ISSUE THREAD

**Issue by jmigual** [matiasdelellis/pdlib-min-test-suite#6]
Hi, when doing the test it returned the following error:

```
bzip2 -d vendor/models/1/shape_predictor_5_face_landmarks.dat.bz2
php scripts/face_detect.php
Welcome to pdlib min test suite for Facerecognition app...

First we try to open the models... Done

Processing file: input/Big Bang Theory.jpg

Fatal error: Uncaught Exception: Error while calling cudaOccupancyMaxPotentialBlockSize(&num_blocks,&num_threads,K) in file /var/www/html/dlib/dlib/cuda/cuda_utils.h:164. code: 8, reason: invalid device function in /var/www/html/pdlib-min-test-suite/scripts/face_detect.php:35
Stack trace:
#0 /var/www/html/pdlib-min-test-suite/scripts/face_detect.php(35): CnnFaceDetection->detect('input/Big Bang ...')
#1 /var/www/html/pdlib-min-test-suite/scripts/face_detect.php(53): findFaces('input/Big Bang ...')
#2 {main}
  thrown in /var/www/html/pdlib-min-test-suite/scripts/face_detect.php on line 35
```

The output of nvidia-smi is

<details>
<summary>nvidia-smi output</summary>

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.141                Driver Version: 390.141                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 520      Off  | 00000000:01:00.0 N/A |                  N/A |
| 40%   42C    P0    N/A /  N/A |      0MiB /   964MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+
```
</details>

And if using `deviceQueryDrv` I get:

<details>
<summary>deviceQueryDrv output</summary>

```
./deviceQueryDrv Starting...

CUDA Device Query (Driver API) statically linked version
Detected 1 CUDA Capable device(s)

Device 0: "GeForce GT 520"
  CUDA Driver Version:                           9.1
  CUDA Capability Major/Minor version number:    2.1
  Total amount of global memory:                 964 MBytes (1011351552 bytes)
  ( 1) Multiprocessors, ( 48) CUDA Cores/MP:     48 CUDA Cores
  GPU Max Clock rate:                            1620 MHz (1.62 GHz)
  Memory Clock rate:                             500 Mhz
  Memory Bus Width:                              64-bit
  L2 Cache Size:                                 65536 bytes
  Max Texture Dimension Sizes                    1D=(65536) 2D=(65536, 65535) 3D=(2048, 2048, 2048)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 32768
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1536
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size (x,y,z):    (65535, 65535, 65535)
  Texture alignment:                             512 bytes
  Maximum memory pitch:                          2147483647 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Concurrent kernel execution:                   Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >
Result = PASS
```

</details>

Note that the normal tests from the https://github.com/goodspb/pdlib/ repository pass properly.

**Comment by matiasdelellis** [comment]
Hi @jmigual 
I have no experience with CUDA, but obviously the problem is there. Until you successfully compile and run the cpp example, you will not be able to use php.

**Comment by jmigual** [comment]
Hi, thanks for your answer, I decided to further test it and noticed that the tests from dlib are the ones failing with cuda so I'll report it there. We can close this.
